backend:
  name: git-gateway
  branch: main
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  # Accueil
  - name: "index"
    title: "Accueil"
    identifier_field: "Accueil"
    extension: "json"
    format: "json"
    label: "Accueil"
    folder: "content/"
    create: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: "Entête"
        name: "header"
        widget: "object"
        fields: 
        - {label: "Titre - rangée 1", name: "titlefirst", widget: "string"}
        - {label: "Titre - rangée 2", name: "titlesecond", widget: "string"}
        - {label: "Image", name: "img", widget: "image", required: true}
      - label: "À propos"
        name: "about"
        widget: "object"
        fields: 
        - {label: "Surtitre", name: "uptitle", widget: "string"}
        - {label: "Titre", name: "title", widget: "string"}
        - {label: "Texte", name: "text", widget: "text"}
        - {label: "Image", name: "img", widget: "image", required: true}
        - label: "Lien"
          name: "link"
          widget: "object"
          fields:
            - {label: "Label", name: "label", widget: "string"}
            - {label: "Url (exemple: /services)", name: "to", widget: "string"}
      - label: "Carousel de texte"
        name: "carouseltext"
        widget: "string"
      - label: "Vidéo"
        name: "video"
        widget: "object"
        fields:
          - {label: "Image", name: "img", widget: "image", required: true}
      - label: "Gallerie"
        name: "gallery"
        widget: "list"
        summary: '{{fields.content.title}}'
        fields:
          - {label: "Image", name: "image", widget: "image", required: true}
          - label: "Contenu"
            name: "content"
            widget: "object"
            fields:
              - {label: "Surtitre", name: "uptitle", widget: "string"}
              - {label: "Titre", name: "title", widget: "string", required: true}
              - {label: "Texte", name: "text", widget: "text"}
      - label: "Infolettre"
        name: "newsletter"
        widget: "object"
        fields:
        - {label: "Contenu", name: "text", widget: "string"}
        - label: "Lien"
          name: "button"
          widget: "object"
          fields:
            - {label: "Libelé", name: "label", widget: "string"}
            - {label: "Url (exemple: /contact)", name: "to", widget: "string"}
  # SERVICES
  - name: "services"
    title: "Services"
    identifier_field: "Services"
    extension: "json"
    format: "json"
    label: "Service"
    folder: "content/services"
    create: true
    slug: '{{slug}}'
    fields:
    - {label: "Titre", name: "title", widget: "string", required: true}
    - {label: "Sommaire", name: "summary", widget: "string"}
    - {label: "Image vedette", name: "featured_image", widget: "image", required: true}
    - label: "Entête"
      name: "header"
      widget: "object"
      fields: 
      - {label: "Image", name: "img", widget: "image", required: true}
    - label: "Contenu"
      name: "content"
      widget: "object"
      fields: 
      - {label: "Introduction", name: "intro", widget: "text"}
      - {label: "Contenu", name: "text", widget: "markdown"}