backend:
  name: git-gateway
  branch: main
media_folder: static/upload
public_folder: /img
collections:
  - name: "index" # Used in routes, e.g., /admin/collections/blog
    identifier_field: "Accueil"
    extension: "json"
    format: "json"
    label: "Accueil" # Used in the UI
    folder: "content/" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "index" # Filename template, e.g., YYYY-MM-DD-title.md
    filter: {field: "language", value: "fr"}
    fields: # The fields for each document, usually in front matter
      - label: "Titre entête"
        name: "headertitle"
        widget: "object"
        fields: 
        - {label: "Rangée 1", name: "first", widget: "string"}
        - {label: "Rangé 2", name: "second", widget: "string"}
      - {label: "Image", name: "headerimage", widget: "image", required: false}