backend:
  name: git-gateway
  branch: main
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "index" # Used in routes, e.g., /admin/collections/blog
    identifier_field: "Accueil"
    extension: "json"
    format: "json"
    label: "Accueil" # Used in the UI
    folder: "content/" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "index" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Entête"
        name: "header"
        widget: "object"
        fields: 
        - {label: "Titre - rangée 1", name: "titlefirst", widget: "string"}
        - {label: "Titre - rangée 2", name: "titlesecond", widget: "string"}
        - {label: "Image", name: "img", widget: "image", required: true}
      - label: "À propos"
        name: "about"
        widget: "object"
        fields: 
        - {label: "Surtitre", name: "uptitle", widget: "string"}
        - {label: "Titre", name: "title", widget: "string"}
        - {label: "Texte", name: "text", widget: "text"}
        - {label: "Image", name: "img", widget: "image", required: true}
      